#!/bin/sh
mkdir -p ./usr/local/lib/egl
cp /system/lib/egl/libEGL_mali.so ./usr/local/lib/egl
cp /system/lib/egl/libGLESv2_mali.so ./usr/local/lib/egl
cp /system/lib/libMali.so ./usr/local/lib
cp /system/lib/libutils.so ./usr/local/lib
cp /system/lib/libcutils.so ./usr/local/lib
cp /system/lib/libbinder.so ./usr/local/lib
cp /system/lib/libui.so ./usr/local/lib
cp /system/lib/libhardware.so ./usr/local/lib
cp /system/lib/libhardware_legacy.so ./usr/local/lib
cp /system/lib/libandroid_runtime.so ./usr/local/lib
cp /system/lib/libpixelflinger.so ./usr/local/lib
cp /system/lib/libexpat.so ./usr/local/lib
cp /system/lib/libnativehelper.so ./usr/local/lib
cp /system/lib/libnetutils.so ./usr/local/lib
cp /system/lib/libgui.so ./usr/local/lib
cp /system/lib/libsurfaceflinger_client.so ./usr/local/lib
cp /system/lib/libcamera_client.so ./usr/local/lib
cp /system/lib/libskiagl.so ./usr/local/lib
cp /system/lib/libskia.so ./usr/local/lib
cp /system/lib/libsqlite.so ./usr/local/lib
cp /system/lib/libdvm.so ./usr/local/lib
cp /system/lib/libETC1.so ./usr/local/lib
cp /system/lib/libsonivox.so ./usr/local/lib
cp /system/lib/libcrypto.so ./usr/local/lib
cp /system/lib/libssl.so ./usr/local/lib
cp /system/lib/libicuuc.so ./usr/local/lib
cp /system/lib/libicui18n.so ./usr/local/lib
cp /system/lib/libmedia.so ./usr/local/lib
cp /system/lib/libwpa_client.so ./usr/local/lib
cp /system/lib/libjpeg.so ./usr/local/lib
cp /system/lib/libnfc_ndef.so ./usr/local/lib
cp /system/lib/libbluedroid.so ./usr/local/lib
cp /system/lib/libdbus.so ./usr/local/lib
cp /system/lib/libemoji.so ./usr/local/lib
cp /system/lib/libm.so ./usr/local/lib
cp /system/lib/libc.so ./usr/local/lib
cp /system/lib/liblog.so ./usr/local/lib
cp /system/lib/libEGL.so ./usr/local/lib
cp /system/lib/libGLESv1_CM.so ./usr/local/lib
cp /system/lib/libdl.so ./usr/local/lib
cp /system/lib/libstdc++.so ./usr/local/lib
cp /system/lib/libz.so ./usr/local/lib
cp /system/lib/libGLESv2.so ./usr/local/lib