#!/bin/sh
cp /system/lib/egl/libEGL_mali.so .
cp /system/lib/egl/libGLESv2_mali.so .
cp /system/lib/libMali.so .
cp /system/lib/libutils.so .
cp /system/lib/libcutils.so .
cp /system/lib/libbinder.so .
cp /system/lib/libui.so .
cp /system/lib/libhardware.so .
cp /system/lib/libhardware_legacy.so .
cp /system/lib/libandroid_runtime.so .
cp /system/lib/libpixelflinger.so .
cp /system/lib/libexpat.so .
cp /system/lib/libnativehelper.so .
cp /system/lib/libnetutils.so .
cp /system/lib/libgui.so .
cp /system/lib/libsurfaceflinger_client.so .
cp /system/lib/libcamera_client.so .
cp /system/lib/libskiagl.so .
cp /system/lib/libskia.so .
cp /system/lib/libsqlite.so .
cp /system/lib/libdvm.so .
cp /system/lib/libETC1.so .
cp /system/lib/libsonivox.so .
cp /system/lib/libcrypto.so .
cp /system/lib/libssl.so .
cp /system/lib/libicuuc.so .
cp /system/lib/libicui18n.so .
cp /system/lib/libmedia.so .
cp /system/lib/libwpa_client.so .
cp /system/lib/libjpeg.so .
cp /system/lib/libnfc_ndef.so .
cp /system/lib/libbluedroid.so .
cp /system/lib/libdbus.so .
cp /system/lib/libemoji.so .
cp /system/lib/libm.so .
cp /system/lib/libc.so .
cp /system/lib/liblog.so .
cp /system/lib/libEGL.so .
cp /system/lib/libGLESv1_CM.so .
cp /system/lib/libdl.so .
cp /system/lib/libstdc++.so .
cp /system/lib/libz.so .
cp /system/lib/libGLESv2.so .